version: '3'

tasks:
  default:
    desc: "Render all documents"
    deps: [render-paper, render-website]

  install-extensions:
    desc: "Install Quarto extensions"
    cmds:
      - quarto add kapsner/authors-block --no-prompt
    status:
      - test -d _extensions/kapsner/authors-block

  render-paper:
    desc: "Render the manuscript"
    deps: [install-extensions]
    cmds:
      - quarto render manuscript/index.qmd
    sources:
      - manuscript/index.qmd
    generates:
      - manuscript/index.html
      - manuscript/index.pdf

  preview:
    desc: "Preview the manuscript with live reload"
    deps: [install-extensions]
    cmds:
      - quarto preview manuscript/index.qmd
    interactive: true

  render-website:
    desc: "Render the guidance website"
    cmds:
      - quarto render
    sources:
      - "*.qmd"
      - "challenges/*.qmd"
      - "methods/*.qmd"
      - "choosing-a-method/*.qmd"
      - "how-to/*.qmd"
      - "case-studies/*.qmd"
      - "community-examples/*.qmd"
      - "resources/*.qmd"
      - "meeting/*.qmd"
      - _quarto.yml
    generates:
      - _site/**

  link-glossary:
    desc: "Link glossary terms in website pages"
    cmds:
      - julia scripts/link-glossary.jl
    sources:
      - "**/*.qmd"
      - scripts/link-glossary.jl

  check-glossary:
    desc: "Check glossary links are up to date"
    cmds:
      - julia scripts/link-glossary.jl --check

  preview-website:
    desc: "Preview the guidance website with live reload"
    cmds:
      - quarto preview
    interactive: true
