version: '3'

tasks:
  default:
    desc: "Render all documents"
    deps: [render-paper, render-website]

  install-extensions:
    desc: "Install Quarto extensions"
    cmds:
      - quarto add kapsner/authors-block --no-prompt
    status:
      - test -d _extensions/kapsner/authors-block

  render-paper:
    desc: "Render the manuscript"
    deps: [install-extensions]
    cmds:
      - quarto render manuscript/paper.qmd
    sources:
      - manuscript/paper.qmd
    generates:
      - manuscript/paper.html
      - manuscript/paper.pdf

  preview:
    desc: "Preview the manuscript with live reload"
    deps: [install-extensions]
    cmds:
      - quarto preview manuscript/paper.qmd
    interactive: true

  render-website:
    desc: "Render the guidance website"
    cmds:
      - quarto render
    sources:
      - "*.qmd"
      - "meeting/*.qmd"
      - "community-examples/*.qmd"
      - _quarto.yml
    generates:
      - _site/**

  preview-website:
    desc: "Preview the guidance website with live reload"
    cmds:
      - quarto preview
    interactive: true
