version: '3'

tasks:
  default:
    desc: "Render all documents"
    deps: [render-paper]

  install-extensions:
    desc: "Install Quarto extensions"
    cmds:
      - quarto add kapsner/authors-block --no-prompt
    status:
      - test -d _extensions/kapsner/authors-block

  render-paper:
    desc: "Render the manuscript"
    deps: [install-extensions]
    cmds:
      - quarto render manuscript/paper.qmd
    sources:
      - manuscript/paper.qmd
    generates:
      - manuscript/paper.html
      - manuscript/paper.pdf

  preview:
    desc: "Preview the manuscript with live reload"
    deps: [install-extensions]
    cmds:
      - quarto preview manuscript/paper.qmd
    interactive: true
